backend:
  name: github
  repo: flypgppvz/PhonesAndRepairs-Final
  branch: tienda-dinamica
  commit_messages:
    create: 'CMS: Crear {{collection}} "{{slug}}"'
    update: 'CMS: Actualizar {{collection}} "{{slug}}"'
    delete: 'CMS: Borrar {{collection}} "{{slug}}"'
    uploadMedia: 'CMS: Subir imagen "{{path}}"'
    deleteMedia: 'CMS: Borrar imagen "{{path}}"'

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "inventario"
    label: "Mis Productos"
    folder: "data"
    extension: "json"
    format: "json"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "number", value_type: "float"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Categoría", name: "category", widget: "select", options: ["iphone", "samsung", "ipad", "smartwatch", "accessories", "consoles", "service"]}
